/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as R404RouteImport } from './app/404'
import { Route as AboutRouteImport } from './app/about'
import { Route as AiGatewayRouteImport } from './app/ai-gateway'
import { Route as ContentRouteImport } from './app/content'
import { Route as ImageRouteImport } from './app/image'
import { Route as ImgRouteImport } from './app/img'
import { Route as KnowledgeRouteImport } from './app/knowledge'
import { Route as LoginRouteImport } from './app/login'
import { Route as MusicRouteImport } from './app/music'
import { Route as ProfileRouteImport } from './app/profile'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as SearchRouteImport } from './app/search'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as ApiBlueprintRouteImport } from './app/api/blueprint'
import { Route as ApiFeedRouteImport } from './app/api/feed'
import { Route as ApiHealthRouteImport } from './app/api/health'
import { Route as ApiKnowledgeRouteImport } from './app/api/knowledge'
import { Route as ApiModelsRouteImport } from './app/api/models'
import { Route as ApiNotificationsRouteImport } from './app/api/notifications'
import { Route as ApiOverviewRouteImport } from './app/api/overview'
import { Route as ApiSearchRouteImport } from './app/api/search'
import { Route as ApiUploadRouteImport } from './app/api/upload'
import { Route as ContentIdRouteImport } from './app/content/$id'
import { Route as KnowledgeCreateRouteImport } from './app/knowledge/create'
import { Route as UserIdRouteImport } from './app/user/$id'
import { Route as ApiAiGatewayKeysRouteImport } from './app/api/ai-gateway/keys'
import { Route as ApiAiGatewayProvidersRouteImport } from './app/api/ai-gateway/providers'
import { Route as ApiAiAccountsRouteImport } from './app/api/ai/accounts'
import { Route as ApiAuthLoginRouteImport } from './app/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './app/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './app/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './app/api/auth/register'
import { Route as ApiAuthSyncRouteImport } from './app/api/auth/sync'
import { Route as ApiAvatarsGenerateRouteImport } from './app/api/avatars/generate'
import { Route as ApiFeedIdRouteImport } from './app/api/feed/$id'
import { Route as ApiFeedSidebarRouteImport } from './app/api/feed/sidebar'
import { Route as ApiImageGenerateRouteImport } from './app/api/image/generate'
import { Route as ApiImagePromptRouteImport } from './app/api/image/prompt'
import { Route as ApiKnowledgeMetaRouteImport } from './app/api/knowledge/meta'
import { Route as ApiKnowledgeParseRouteImport } from './app/api/knowledge/parse'
import { Route as ApiMusicGenerateRouteImport } from './app/api/music/generate'
import { Route as ApiMusicPublishRouteImport } from './app/api/music/publish'
import { Route as ApiUserIdRouteImport } from './app/api/user/$id'
import { Route as ApiUserProfileRouteImport } from './app/api/user/profile'
import { Route as ApiV1SplatRouteImport } from './app/api/v1/$'
import { Route as ApiFeedIdCommentsRouteImport } from './app/api/feed/$id/comments'
import { Route as ApiFeedIdLikeRouteImport } from './app/api/feed/$id/like'
import { Route as ApiUserIdFollowRouteImport } from './app/api/user/$id/follow'
import { Route as ApiUserIdPublicationsRouteImport } from './app/api/user/$id/publications'
import { Route as ApiFeedCommentsCommentIdLikeRouteImport } from './app/api/feed/comments/$commentId/like'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGatewayRoute = AiGatewayRouteImport.update({
  id: '/ai-gateway',
  path: '/ai-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgRoute = ImgRouteImport.update({
  id: '/img',
  path: '/img',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintRoute = ApiBlueprintRouteImport.update({
  id: '/api/blueprint',
  path: '/api/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeRoute = ApiKnowledgeRouteImport.update({
  id: '/api/knowledge',
  path: '/api/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentRoute,
} as any)
const KnowledgeCreateRoute = KnowledgeCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGatewayKeysRoute = ApiAiGatewayKeysRouteImport.update({
  id: '/api/ai-gateway/keys',
  path: '/api/ai-gateway/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGatewayProvidersRoute = ApiAiGatewayProvidersRouteImport.update({
  id: '/api/ai-gateway/providers',
  path: '/api/ai-gateway/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAccountsRoute = ApiAiAccountsRouteImport.update({
  id: '/api/ai/accounts',
  path: '/api/ai/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSyncRoute = ApiAuthSyncRouteImport.update({
  id: '/api/auth/sync',
  path: '/api/auth/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarsGenerateRoute = ApiAvatarsGenerateRouteImport.update({
  id: '/api/avatars/generate',
  path: '/api/avatars/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedIdRoute = ApiFeedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedSidebarRoute = ApiFeedSidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiImageGenerateRoute = ApiImageGenerateRouteImport.update({
  id: '/api/image/generate',
  path: '/api/image/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagePromptRoute = ApiImagePromptRouteImport.update({
  id: '/api/image/prompt',
  path: '/api/image/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeMetaRoute = ApiKnowledgeMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => ApiKnowledgeRoute,
} as any)
const ApiKnowledgeParseRoute = ApiKnowledgeParseRouteImport.update({
  id: '/parse',
  path: '/parse',
  getParentRoute: () => ApiKnowledgeRoute,
} as any)
const ApiMusicGenerateRoute = ApiMusicGenerateRouteImport.update({
  id: '/api/music/generate',
  path: '/api/music/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicPublishRoute = ApiMusicPublishRouteImport.update({
  id: '/api/music/publish',
  path: '/api/music/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserIdRoute = ApiUserIdRouteImport.update({
  id: '/api/user/$id',
  path: '/api/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedIdCommentsRoute = ApiFeedIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiFeedIdRoute,
} as any)
const ApiFeedIdLikeRoute = ApiFeedIdLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiFeedIdRoute,
} as any)
const ApiUserIdFollowRoute = ApiUserIdFollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => ApiUserIdRoute,
} as any)
const ApiUserIdPublicationsRoute = ApiUserIdPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => ApiUserIdRoute,
} as any)
const ApiFeedCommentsCommentIdLikeRoute =
  ApiFeedCommentsCommentIdLikeRouteImport.update({
    id: '/comments/$commentId/like',
    path: '/comments/$commentId/like',
    getParentRoute: () => ApiFeedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/ai-gateway': typeof AiGatewayRoute
  '/content': typeof ContentRouteWithChildren
  '/image': typeof ImageRoute
  '/img': typeof ImgRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/content/$id': typeof ContentIdRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/user/$id': typeof UserIdRoute
  '/api/ai-gateway/keys': typeof ApiAiGatewayKeysRoute
  '/api/ai-gateway/providers': typeof ApiAiGatewayProvidersRoute
  '/api/ai/accounts': typeof ApiAiAccountsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/avatars/generate': typeof ApiAvatarsGenerateRoute
  '/api/feed/$id': typeof ApiFeedIdRouteWithChildren
  '/api/feed/sidebar': typeof ApiFeedSidebarRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/image/prompt': typeof ApiImagePromptRoute
  '/api/knowledge/meta': typeof ApiKnowledgeMetaRoute
  '/api/knowledge/parse': typeof ApiKnowledgeParseRoute
  '/api/music/generate': typeof ApiMusicGenerateRoute
  '/api/music/publish': typeof ApiMusicPublishRoute
  '/api/user/$id': typeof ApiUserIdRouteWithChildren
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/feed/$id/comments': typeof ApiFeedIdCommentsRoute
  '/api/feed/$id/like': typeof ApiFeedIdLikeRoute
  '/api/user/$id/follow': typeof ApiUserIdFollowRoute
  '/api/user/$id/publications': typeof ApiUserIdPublicationsRoute
  '/api/feed/comments/$commentId/like': typeof ApiFeedCommentsCommentIdLikeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/ai-gateway': typeof AiGatewayRoute
  '/content': typeof ContentRouteWithChildren
  '/image': typeof ImageRoute
  '/img': typeof ImgRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/content/$id': typeof ContentIdRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/user/$id': typeof UserIdRoute
  '/api/ai-gateway/keys': typeof ApiAiGatewayKeysRoute
  '/api/ai-gateway/providers': typeof ApiAiGatewayProvidersRoute
  '/api/ai/accounts': typeof ApiAiAccountsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/avatars/generate': typeof ApiAvatarsGenerateRoute
  '/api/feed/$id': typeof ApiFeedIdRouteWithChildren
  '/api/feed/sidebar': typeof ApiFeedSidebarRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/image/prompt': typeof ApiImagePromptRoute
  '/api/knowledge/meta': typeof ApiKnowledgeMetaRoute
  '/api/knowledge/parse': typeof ApiKnowledgeParseRoute
  '/api/music/generate': typeof ApiMusicGenerateRoute
  '/api/music/publish': typeof ApiMusicPublishRoute
  '/api/user/$id': typeof ApiUserIdRouteWithChildren
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/feed/$id/comments': typeof ApiFeedIdCommentsRoute
  '/api/feed/$id/like': typeof ApiFeedIdLikeRoute
  '/api/user/$id/follow': typeof ApiUserIdFollowRoute
  '/api/user/$id/publications': typeof ApiUserIdPublicationsRoute
  '/api/feed/comments/$commentId/like': typeof ApiFeedCommentsCommentIdLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/ai-gateway': typeof AiGatewayRoute
  '/content': typeof ContentRouteWithChildren
  '/image': typeof ImageRoute
  '/img': typeof ImgRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/knowledge': typeof ApiKnowledgeRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/content/$id': typeof ContentIdRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/user/$id': typeof UserIdRoute
  '/api/ai-gateway/keys': typeof ApiAiGatewayKeysRoute
  '/api/ai-gateway/providers': typeof ApiAiGatewayProvidersRoute
  '/api/ai/accounts': typeof ApiAiAccountsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/avatars/generate': typeof ApiAvatarsGenerateRoute
  '/api/feed/$id': typeof ApiFeedIdRouteWithChildren
  '/api/feed/sidebar': typeof ApiFeedSidebarRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/image/prompt': typeof ApiImagePromptRoute
  '/api/knowledge/meta': typeof ApiKnowledgeMetaRoute
  '/api/knowledge/parse': typeof ApiKnowledgeParseRoute
  '/api/music/generate': typeof ApiMusicGenerateRoute
  '/api/music/publish': typeof ApiMusicPublishRoute
  '/api/user/$id': typeof ApiUserIdRouteWithChildren
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/feed/$id/comments': typeof ApiFeedIdCommentsRoute
  '/api/feed/$id/like': typeof ApiFeedIdLikeRoute
  '/api/user/$id/follow': typeof ApiUserIdFollowRoute
  '/api/user/$id/publications': typeof ApiUserIdPublicationsRoute
  '/api/feed/comments/$commentId/like': typeof ApiFeedCommentsCommentIdLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/ai-gateway'
    | '/content'
    | '/image'
    | '/img'
    | '/knowledge'
    | '/login'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/blueprint'
    | '/api/feed'
    | '/api/health'
    | '/api/knowledge'
    | '/api/models'
    | '/api/notifications'
    | '/api/overview'
    | '/api/search'
    | '/api/upload'
    | '/content/$id'
    | '/knowledge/create'
    | '/user/$id'
    | '/api/ai-gateway/keys'
    | '/api/ai-gateway/providers'
    | '/api/ai/accounts'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/sync'
    | '/api/avatars/generate'
    | '/api/feed/$id'
    | '/api/feed/sidebar'
    | '/api/image/generate'
    | '/api/image/prompt'
    | '/api/knowledge/meta'
    | '/api/knowledge/parse'
    | '/api/music/generate'
    | '/api/music/publish'
    | '/api/user/$id'
    | '/api/user/profile'
    | '/api/v1/$'
    | '/api/feed/$id/comments'
    | '/api/feed/$id/like'
    | '/api/user/$id/follow'
    | '/api/user/$id/publications'
    | '/api/feed/comments/$commentId/like'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/ai-gateway'
    | '/content'
    | '/image'
    | '/img'
    | '/knowledge'
    | '/login'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/blueprint'
    | '/api/feed'
    | '/api/health'
    | '/api/knowledge'
    | '/api/models'
    | '/api/notifications'
    | '/api/overview'
    | '/api/search'
    | '/api/upload'
    | '/content/$id'
    | '/knowledge/create'
    | '/user/$id'
    | '/api/ai-gateway/keys'
    | '/api/ai-gateway/providers'
    | '/api/ai/accounts'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/sync'
    | '/api/avatars/generate'
    | '/api/feed/$id'
    | '/api/feed/sidebar'
    | '/api/image/generate'
    | '/api/image/prompt'
    | '/api/knowledge/meta'
    | '/api/knowledge/parse'
    | '/api/music/generate'
    | '/api/music/publish'
    | '/api/user/$id'
    | '/api/user/profile'
    | '/api/v1/$'
    | '/api/feed/$id/comments'
    | '/api/feed/$id/like'
    | '/api/user/$id/follow'
    | '/api/user/$id/publications'
    | '/api/feed/comments/$commentId/like'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/ai-gateway'
    | '/content'
    | '/image'
    | '/img'
    | '/knowledge'
    | '/login'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/blueprint'
    | '/api/feed'
    | '/api/health'
    | '/api/knowledge'
    | '/api/models'
    | '/api/notifications'
    | '/api/overview'
    | '/api/search'
    | '/api/upload'
    | '/content/$id'
    | '/knowledge/create'
    | '/user/$id'
    | '/api/ai-gateway/keys'
    | '/api/ai-gateway/providers'
    | '/api/ai/accounts'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/sync'
    | '/api/avatars/generate'
    | '/api/feed/$id'
    | '/api/feed/sidebar'
    | '/api/image/generate'
    | '/api/image/prompt'
    | '/api/knowledge/meta'
    | '/api/knowledge/parse'
    | '/api/music/generate'
    | '/api/music/publish'
    | '/api/user/$id'
    | '/api/user/profile'
    | '/api/v1/$'
    | '/api/feed/$id/comments'
    | '/api/feed/$id/like'
    | '/api/user/$id/follow'
    | '/api/user/$id/publications'
    | '/api/feed/comments/$commentId/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AiGatewayRoute: typeof AiGatewayRoute
  ContentRoute: typeof ContentRouteWithChildren
  ImageRoute: typeof ImageRoute
  ImgRoute: typeof ImgRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  MusicRoute: typeof MusicRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBlueprintRoute: typeof ApiBlueprintRoute
  ApiFeedRoute: typeof ApiFeedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiKnowledgeRoute: typeof ApiKnowledgeRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  UserIdRoute: typeof UserIdRoute
  ApiAiGatewayKeysRoute: typeof ApiAiGatewayKeysRoute
  ApiAiGatewayProvidersRoute: typeof ApiAiGatewayProvidersRoute
  ApiAiAccountsRoute: typeof ApiAiAccountsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSyncRoute: typeof ApiAuthSyncRoute
  ApiAvatarsGenerateRoute: typeof ApiAvatarsGenerateRoute
  ApiImageGenerateRoute: typeof ApiImageGenerateRoute
  ApiImagePromptRoute: typeof ApiImagePromptRoute
  ApiMusicGenerateRoute: typeof ApiMusicGenerateRoute
  ApiMusicPublishRoute: typeof ApiMusicPublishRoute
  ApiUserIdRoute: typeof ApiUserIdRouteWithChildren
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-gateway': {
      id: '/ai-gateway'
      path: '/ai-gateway'
      fullPath: '/ai-gateway'
      preLoaderRoute: typeof AiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img': {
      id: '/img'
      path: '/img'
      fullPath: '/img'
      preLoaderRoute: typeof ImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint': {
      id: '/api/blueprint'
      path: '/api/blueprint'
      fullPath: '/api/blueprint'
      preLoaderRoute: typeof ApiBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge': {
      id: '/api/knowledge'
      path: '/api/knowledge'
      fullPath: '/api/knowledge'
      preLoaderRoute: typeof ApiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/knowledge/create': {
      id: '/knowledge/create'
      path: '/create'
      fullPath: '/knowledge/create'
      preLoaderRoute: typeof KnowledgeCreateRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-gateway/keys': {
      id: '/api/ai-gateway/keys'
      path: '/api/ai-gateway/keys'
      fullPath: '/api/ai-gateway/keys'
      preLoaderRoute: typeof ApiAiGatewayKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-gateway/providers': {
      id: '/api/ai-gateway/providers'
      path: '/api/ai-gateway/providers'
      fullPath: '/api/ai-gateway/providers'
      preLoaderRoute: typeof ApiAiGatewayProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/accounts': {
      id: '/api/ai/accounts'
      path: '/api/ai/accounts'
      fullPath: '/api/ai/accounts'
      preLoaderRoute: typeof ApiAiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sync': {
      id: '/api/auth/sync'
      path: '/api/auth/sync'
      fullPath: '/api/auth/sync'
      preLoaderRoute: typeof ApiAuthSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatars/generate': {
      id: '/api/avatars/generate'
      path: '/api/avatars/generate'
      fullPath: '/api/avatars/generate'
      preLoaderRoute: typeof ApiAvatarsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/$id': {
      id: '/api/feed/$id'
      path: '/$id'
      fullPath: '/api/feed/$id'
      preLoaderRoute: typeof ApiFeedIdRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/sidebar': {
      id: '/api/feed/sidebar'
      path: '/sidebar'
      fullPath: '/api/feed/sidebar'
      preLoaderRoute: typeof ApiFeedSidebarRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/image/generate': {
      id: '/api/image/generate'
      path: '/api/image/generate'
      fullPath: '/api/image/generate'
      preLoaderRoute: typeof ApiImageGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/prompt': {
      id: '/api/image/prompt'
      path: '/api/image/prompt'
      fullPath: '/api/image/prompt'
      preLoaderRoute: typeof ApiImagePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/meta': {
      id: '/api/knowledge/meta'
      path: '/meta'
      fullPath: '/api/knowledge/meta'
      preLoaderRoute: typeof ApiKnowledgeMetaRouteImport
      parentRoute: typeof ApiKnowledgeRoute
    }
    '/api/knowledge/parse': {
      id: '/api/knowledge/parse'
      path: '/parse'
      fullPath: '/api/knowledge/parse'
      preLoaderRoute: typeof ApiKnowledgeParseRouteImport
      parentRoute: typeof ApiKnowledgeRoute
    }
    '/api/music/generate': {
      id: '/api/music/generate'
      path: '/api/music/generate'
      fullPath: '/api/music/generate'
      preLoaderRoute: typeof ApiMusicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/publish': {
      id: '/api/music/publish'
      path: '/api/music/publish'
      fullPath: '/api/music/publish'
      preLoaderRoute: typeof ApiMusicPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$id': {
      id: '/api/user/$id'
      path: '/api/user/$id'
      fullPath: '/api/user/$id'
      preLoaderRoute: typeof ApiUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/$id/comments': {
      id: '/api/feed/$id/comments'
      path: '/comments'
      fullPath: '/api/feed/$id/comments'
      preLoaderRoute: typeof ApiFeedIdCommentsRouteImport
      parentRoute: typeof ApiFeedIdRoute
    }
    '/api/feed/$id/like': {
      id: '/api/feed/$id/like'
      path: '/like'
      fullPath: '/api/feed/$id/like'
      preLoaderRoute: typeof ApiFeedIdLikeRouteImport
      parentRoute: typeof ApiFeedIdRoute
    }
    '/api/user/$id/follow': {
      id: '/api/user/$id/follow'
      path: '/follow'
      fullPath: '/api/user/$id/follow'
      preLoaderRoute: typeof ApiUserIdFollowRouteImport
      parentRoute: typeof ApiUserIdRoute
    }
    '/api/user/$id/publications': {
      id: '/api/user/$id/publications'
      path: '/publications'
      fullPath: '/api/user/$id/publications'
      preLoaderRoute: typeof ApiUserIdPublicationsRouteImport
      parentRoute: typeof ApiUserIdRoute
    }
    '/api/feed/comments/$commentId/like': {
      id: '/api/feed/comments/$commentId/like'
      path: '/comments/$commentId/like'
      fullPath: '/api/feed/comments/$commentId/like'
      preLoaderRoute: typeof ApiFeedCommentsCommentIdLikeRouteImport
      parentRoute: typeof ApiFeedRoute
    }
  }
}

interface ContentRouteChildren {
  ContentIdRoute: typeof ContentIdRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentIdRoute: ContentIdRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeCreateRoute: typeof KnowledgeCreateRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeCreateRoute: KnowledgeCreateRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ApiFeedIdRouteChildren {
  ApiFeedIdCommentsRoute: typeof ApiFeedIdCommentsRoute
  ApiFeedIdLikeRoute: typeof ApiFeedIdLikeRoute
}

const ApiFeedIdRouteChildren: ApiFeedIdRouteChildren = {
  ApiFeedIdCommentsRoute: ApiFeedIdCommentsRoute,
  ApiFeedIdLikeRoute: ApiFeedIdLikeRoute,
}

const ApiFeedIdRouteWithChildren = ApiFeedIdRoute._addFileChildren(
  ApiFeedIdRouteChildren,
)

interface ApiFeedRouteChildren {
  ApiFeedIdRoute: typeof ApiFeedIdRouteWithChildren
  ApiFeedSidebarRoute: typeof ApiFeedSidebarRoute
  ApiFeedCommentsCommentIdLikeRoute: typeof ApiFeedCommentsCommentIdLikeRoute
}

const ApiFeedRouteChildren: ApiFeedRouteChildren = {
  ApiFeedIdRoute: ApiFeedIdRouteWithChildren,
  ApiFeedSidebarRoute: ApiFeedSidebarRoute,
  ApiFeedCommentsCommentIdLikeRoute: ApiFeedCommentsCommentIdLikeRoute,
}

const ApiFeedRouteWithChildren =
  ApiFeedRoute._addFileChildren(ApiFeedRouteChildren)

interface ApiKnowledgeRouteChildren {
  ApiKnowledgeMetaRoute: typeof ApiKnowledgeMetaRoute
  ApiKnowledgeParseRoute: typeof ApiKnowledgeParseRoute
}

const ApiKnowledgeRouteChildren: ApiKnowledgeRouteChildren = {
  ApiKnowledgeMetaRoute: ApiKnowledgeMetaRoute,
  ApiKnowledgeParseRoute: ApiKnowledgeParseRoute,
}

const ApiKnowledgeRouteWithChildren = ApiKnowledgeRoute._addFileChildren(
  ApiKnowledgeRouteChildren,
)

interface ApiUserIdRouteChildren {
  ApiUserIdFollowRoute: typeof ApiUserIdFollowRoute
  ApiUserIdPublicationsRoute: typeof ApiUserIdPublicationsRoute
}

const ApiUserIdRouteChildren: ApiUserIdRouteChildren = {
  ApiUserIdFollowRoute: ApiUserIdFollowRoute,
  ApiUserIdPublicationsRoute: ApiUserIdPublicationsRoute,
}

const ApiUserIdRouteWithChildren = ApiUserIdRoute._addFileChildren(
  ApiUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AiGatewayRoute: AiGatewayRoute,
  ContentRoute: ContentRouteWithChildren,
  ImageRoute: ImageRoute,
  ImgRoute: ImgRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  MusicRoute: MusicRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBlueprintRoute: ApiBlueprintRoute,
  ApiFeedRoute: ApiFeedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiKnowledgeRoute: ApiKnowledgeRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  UserIdRoute: UserIdRoute,
  ApiAiGatewayKeysRoute: ApiAiGatewayKeysRoute,
  ApiAiGatewayProvidersRoute: ApiAiGatewayProvidersRoute,
  ApiAiAccountsRoute: ApiAiAccountsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSyncRoute: ApiAuthSyncRoute,
  ApiAvatarsGenerateRoute: ApiAvatarsGenerateRoute,
  ApiImageGenerateRoute: ApiImageGenerateRoute,
  ApiImagePromptRoute: ApiImagePromptRoute,
  ApiMusicGenerateRoute: ApiMusicGenerateRoute,
  ApiMusicPublishRoute: ApiMusicPublishRoute,
  ApiUserIdRoute: ApiUserIdRouteWithChildren,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
